######################## 后端应用配置文件 ########################

# 全局公共配置
global:
  # 默认语言，可以选zh，en
  # ? [TODO): en现在还没有翻译，暂时懒得翻译了
  defaultLanguage: zh
  enableSwagger: true
  # 节流阀门配置。默认为 60000 毫秒内最多 300 次请求，可以开大点
  throttler:
    ttl: 60
    limit: 300
  # 数据源配置
  datasource:
    # 数据库类型，目前只支持mysql
    mysql:
      host: localhost
      port: 3306
      username: unknown
      password: unknown
      database: unknown
      entityPrefix: element_
      logging: true
    # redis 配置
    redis:
      host: localhost
      port: 6379
      # db: 0
      keyPrefix: element_
      password: unknown
  # 邮箱配置
  email:
    # smtp地址，一行写完就行
    transport: smtp://app@smtp.qq.com
    # 发件人
    from: '"腕上心电社区" <gczgroup@qq.com>'
  jwt:
    # 保密，不要泄露
    secret: JWTSERCRET
    # token过期时间 可以用这个来控制登录时长
    expiresIn: 30d

# 账户微服务配置
passport:
  # 账户微服务 端口
  port: 3000

####################### 以下内容由开发者修改 #######################

scripts:
  buildDeps:
    commands:
      - pnpm build:shared
      - pnpm build:auth
      - pnpm build:database
      - pnpm build:swagger
      - pnpm build:validator
